spring:
  data:
    mongodb:
      uri: mongodb+srv://root:toor@testdb.cpxr8qa.mongodb.net/?retryWrites=true&w=majority
      database: devDB
      authentication-database: devDB
      
  profiles:
    active: PROD
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
  jpa:
    show-sql: true
    
springdoc:
  api-docs:
    groups:
      enabled: true